name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration:
    name: Integration test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Conan
        run: pip install conan

      - name: Create Conan profile
        run: conan profile detect --force

      - name: Set build dir
        id: vars2
        run: echo "BUILD_DIR=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: conan install . --output-folder=${{ steps.vars2.outputs.BUILD_DIR }} --build=missing -s build_type=Release

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.vars2.outputs.BUILD_DIR }}
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_INTEGRATION=ON
          -DCMAKE_TOOLCHAIN_FILE=${{ steps.vars2.outputs.BUILD_DIR }}/conan_toolchain.cmake
          -S ${{ github.workspace }}

      - name: Build integration test
        run: >
          cmake --build ${{ steps.vars2.outputs.BUILD_DIR }}
          --config Release
          --target integration_tests

      - name: Run integration test
        working-directory: ${{ steps.vars2.outputs.BUILD_DIR }}
        run: ctest -C Release -L integration --output-on-failure